### ISSUE TITLE
User Profile View

### ISSUE THREAD

**Issue by catilac** [catilac/quinoa#2]
No reasonable wireframes for this page at the moment:
#### USER MODEL
- first name, last name 
- gender
- birthday
- weight
- height
- photo
- preferences (list: "dietary", "fitness")
- [x] Build a page with a form for all these elements
- [ ] Tapping on Profile photo will take you through camera flow ("Use existing or take new photo")
- [ ] The preferences list will basic until we get those wireframes. A checkbox thing works? Hemen likes to be creative, so I'm excited :)

**Comment by hchhatbar** [comment]
basic profile form completed
