### ISSUE TITLE
My Plan View

### ISSUE THREAD

**Issue by catilac** [catilac/quinoa#6]
https://www.dropbox.com/s/q7urs1xdzaknfmd/04%20User%20View%20-%20My%20Plan%20Day%20View.png
- [x] Show plan for Today
- [x] UI for navigating between days past and Today
- [x] Check list for checking items off

**Comment by grnbeagle** [comment]
![my plan view](https://cloud.githubusercontent.com/assets/91947/3492538/acc8777c-05ab-11e4-9ccd-c8ce8b6b8105.gif)

Done! This is in `MyPlanViewController`.
