### ISSUE TITLE
My Plan Overview

### ISSUE THREAD

**Issue by catilac** [catilac/quinoa#7]
https://www.dropbox.com/s/olh9j6h1jfqizhf/05%20User%20View%20-%20My%20Plan%20Overview.png
#### Daily Plan list view
- [x] Collapsable list view for Plan completion.
- [x] Collapsed list view cell is checked if user has done all items on plan for that day
- [x] expanding cell will show the details items, and whether they are completed or not.
#### Graph
- [x] Task completion graph, will be a histogram, of dates on the X-Axis, and numCompleted/TotalItems on the Y-Axis
- [ ] Task completion graph scrolls left and right

**Comment by catilac** [comment]
@grnbeagle - this is a large one. We can both work on this if it comes down to it!

**Comment by grnbeagle** [comment]
@chiragrules - :+1:

**Comment by grnbeagle** [comment]
![my plan view overview](https://cloud.githubusercontent.com/assets/91947/3492586/a222966c-05ac-11e4-8439-703aeb20ab8d.gif)

This is in `MyPlanOverviewViewController`.
